const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync, spawn } = require('child_process');
const { pathToFileURL, fileURLToPath } = require('url');

const ROOT = path.resolve(__dirname, '../..');
const DECOMPILED_BODY = 'return List.of(prefix + values.length);';
const TIMEOUT_MS = 30000;

function executableName(name) {
    return process.platform === 'win32' ? `${name}.exe` : name;
}

function validJdk(home) {
    return Boolean(
        home &&
        path.isAbsolute(home) &&
        fs.existsSync(path.join(home, 'release')) &&
        fs.existsSync(path.join(home, 'bin', executableName('java'))) &&
        fs.existsSync(path.join(home, 'bin', executableName('jar')))
    );
}

function discoverJdkHome() {
    const configured = process.env.JAVA_HOME;
    if (validJdk(configured)) return fs.realpathSync(configured);

    if (process.platform === 'darwin') {
        try {
            const discovered = execFileSync('/usr/libexec/java_home', [], {
                encoding: 'utf8',
                stdio: ['ignore', 'pipe', 'ignore']
            }).trim();
            if (validJdk(discovered)) return fs.realpathSync(discovered);
        } catch {
            // Continue to PATH discovery.
        }
    }

    try {
        const lookup = process.platform === 'win32'
            ? execFileSync('where.exe', ['java.exe'], { encoding: 'utf8' }).split(/\r?\n/)[0]
            : execFileSync('sh', ['-c', 'command -v java'], { encoding: 'utf8' }).trim();
        const java = fs.realpathSync(lookup);
        const home = path.dirname(path.dirname(java));
        if (validJdk(home)) return home;
    } catch {
        // Report one actionable error below.
    }

    throw new Error(
        'Packaged JRuby navigation smoke requires a full JDK with java, jar, and release metadata. Set JAVA_HOME to the exact JDK.'
    );
}

function createFixture(parent) {
    const project = path.join(parent, 'jruby-project');
    const classRoot = path.join(parent, 'classes');
    const classFile = path.join(classRoot, 'fixtures', 'RichFixture.class');
    const jarFile = path.join(project, 'lib', 'rich.jar');
    const jrubyExecutable = path.join(
        parent,
        'jruby-9.2.21.0',
        'bin',
        executableName('jruby')
    );
    const javaSourceFile = path.join(project, 'src', 'main', 'java', 'fixtures', 'RichFixture.java');
    const javaSource = [
        'package fixtures;',
        '',
        'public class RichFixture {',
        '    // The checked bytecode contains members generated by a separate fixture build.',
        '}',
        ''
    ].join('\n');
    const sourceFile = path.join(project, 'imports.rb');
    const source = [
        'java_import fixtures.RichFixture',
        'RICH = RichFixture.new(nil)',
        "VALUE = RICH.java_send(:combine, [java.lang.String, Java::int[]], 'x', [1])",
        "DIRECT = RICH.combine('x', [1])",
        ''
    ].join('\n');

    fs.mkdirSync(path.dirname(classFile), { recursive: true });
    fs.mkdirSync(path.dirname(jarFile), { recursive: true });
    fs.mkdirSync(path.dirname(jrubyExecutable), { recursive: true });
    fs.mkdirSync(path.dirname(javaSourceFile), { recursive: true });
    const hex = fs
        .readFileSync(path.join(ROOT, 'crates/jvm-metadata/fixtures/rich_fixture.class.hex'), 'utf8')
        .replace(/\s+/g, '');
    if (hex.length === 0 || hex.length % 2 !== 0 || !/^[0-9a-f]+$/i.test(hex)) {
        throw new Error('JRuby navigation class fixture is not valid hexadecimal bytecode');
    }
    fs.writeFileSync(classFile, Buffer.from(hex, 'hex'));
    fs.writeFileSync(path.join(project, 'Gemfile'), '');
    fs.writeFileSync(sourceFile, source);
    fs.writeFileSync(javaSourceFile, javaSource);
    fs.writeFileSync(
        jrubyExecutable,
        process.platform === 'win32' ? '' : '#!/bin/sh\nprintf \'[]\\n\'\n'
    );
    if (process.platform !== 'win32') fs.chmodSync(jrubyExecutable, 0o755);

    const javaHome = discoverJdkHome();
    execFileSync(
        path.join(javaHome, 'bin', executableName('jar')),
        ['--create', '--file', jarFile, '-C', classRoot, 'fixtures/RichFixture.class'],
        { stdio: ['ignore', 'pipe', 'pipe'] }
    );
    const directLine = source.split('\n')[3];
    const directMethodCharacter = directLine.indexOf('combine');
    return {
        project,
        sourceFile,
        source,
        javaSourceFile,
        javaSource,
        jrubyExecutable,
        javaHome,
        positions: {
            completion: { line: 3, character: directMethodCharacter },
            method: { line: 3, character: directMethodCharacter + 1 },
            signature: { line: 3, character: directLine.indexOf('[1]') + 1 }
        }
    };
}

function textInLspRange(text, range) {
    if (!range?.start || !range?.end) return '';
    const lines = text.split('\n');
    function offset(position) {
        if (
            !Number.isInteger(position.line) ||
            !Number.isInteger(position.character) ||
            position.line < 0 ||
            position.line >= lines.length ||
            position.character < 0 ||
            position.character > lines[position.line].length
        ) {
            return null;
        }
        let value = 0;
        for (let line = 0; line < position.line; line += 1) {
            value += lines[line].length + 1;
        }
        return value + position.character;
    }
    const start = offset(range.start);
    const end = offset(range.end);
    return start === null || end === null || end < start ? '' : text.slice(start, end);
}

function lspFrame(message) {
    const body = JSON.stringify(message);
    return `Content-Length: ${Buffer.byteLength(body)}\r\n\r\n${body}`;
}

function runPackagedJrubyNavigationSmoke(options) {
    const {
        command,
        args = [],
        env = {},
        label,
        initializationOptions = {}
    } = options;
    const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'ruby-fast-lsp-jruby-package-'));
    const fixture = createFixture(temp);
    const cacheRoot = path.join(temp, 'cache');
    const projectUri = pathToFileURL(`${fixture.project}${path.sep}`).href;
    const sourceUri = pathToFileURL(fixture.sourceFile).href;
    const runtimeRoot = `${fixture.project}${path.sep}`;
    const childEnv = {
        ...process.env,
        ...env,
        RUST_LOG: 'error',
        RUBY_FAST_LSP_CACHE_DIR: cacheRoot
    };
    delete childEnv.RUBY_FAST_LSP_CFR_JAR;
    delete childEnv.RUBY_FAST_LSP_EXTENSION_PATHS;
    delete childEnv.RUBY_FAST_LSP_EXTENSION_DIRS;

    return new Promise((resolve, reject) => {
        const child = spawn(command, args, {
            cwd: temp,
            env: childEnv,
            stdio: ['pipe', 'pipe', 'pipe']
        });
        let stdout = Buffer.alloc(0);
        let stderr = '';
        let settled = false;
        let indexingEnded = false;
        let definitionAttempts = 0;
        let nextRequestId = 10;
        const definitionRequestIds = new Set();
        const classDefinitionRequestIds = new Set();
        const statusRequestId = 1000;
        const semanticRequestIds = {
            hover: 1001,
            completion: 1002,
            signature: 1003,
            references: 1004
        };
        const semanticEvidence = new Set();
        let implementationLocated = false;
        let timer;

        function cleanup(error) {
            if (settled) return;
            settled = true;
            clearTimeout(timer);
            child.kill();
            fs.rmSync(temp, { recursive: true, force: true });
            if (error) reject(new Error(`${error.message}\n${stderr}`));
            else resolve();
        }

        function send(message) {
            child.stdin.write(lspFrame(message));
        }

        function requestDefinition() {
            definitionAttempts += 1;
            const id = nextRequestId++;
            definitionRequestIds.add(id);
            send({
                jsonrpc: '2.0',
                id,
                method: 'textDocument/definition',
                params: {
                    textDocument: { uri: sourceUri },
                    position: { line: 2, character: 25 }
                }
            });
        }

        function requestClassDefinition() {
            const id = nextRequestId++;
            classDefinitionRequestIds.add(id);
            send({
                jsonrpc: '2.0',
                id,
                method: 'textDocument/definition',
                params: {
                    textDocument: { uri: sourceUri },
                    position: { line: 0, character: 24 }
                }
            });
        }

        function openAndRequestDefinition() {
            send({
                jsonrpc: '2.0',
                method: 'textDocument/didOpen',
                params: {
                    textDocument: {
                        uri: sourceUri,
                        languageId: 'ruby',
                        version: 1,
                        text: fixture.source
                    }
                }
            });
            requestDefinition();
        }

        function validateDefinition(response) {
            const raw = response.result;
            const locations = Array.isArray(raw)
                ? raw
                : raw && Array.isArray(raw.items)
                    ? raw.items
                    : raw
                        ? [raw]
                        : [];
            const implementation = locations.find(location => {
                const uri = location?.uri || location?.targetUri;
                const range = location?.range || location?.targetRange;
                if (!uri?.startsWith('file:')) return false;
                const target = fileURLToPath(uri);
                if (
                    !target.startsWith(cacheRoot) ||
                    target.startsWith(fixture.project) ||
                    !fs.existsSync(target)
                ) {
                    return false;
                }
                const content = fs.readFileSync(target, 'utf8');
                return target.startsWith(cacheRoot) &&
                    !target.startsWith(fixture.project) &&
                    textInLspRange(content, range).includes(DECOMPILED_BODY);
            });
            if (implementation) {
                implementationLocated = true;
                requestClassDefinition();
                return;
            }
            if (definitionAttempts >= 20) {
                cleanup(new Error(
                    `${label} did not navigate to the packaged decompiled implementation after ${definitionAttempts} attempts: ${JSON.stringify(raw)}`
                ));
                return;
            }
            setTimeout(requestDefinition, 100);
        }

        function validateClassDefinition(response) {
            const raw = response.result;
            const locations = Array.isArray(raw) ? raw : raw ? [raw] : [];
            const exactSource = locations.find(location => {
                const uri = location?.uri || location?.targetUri;
                const range = location?.range || location?.targetRange;
                if (!uri?.startsWith('file:')) return false;
                const target = fileURLToPath(uri);
                return fs.realpathSync(target) === fs.realpathSync(fixture.javaSourceFile) &&
                    textInLspRange(fixture.javaSource, range).includes('class RichFixture');
            });
            if (!exactSource) {
                cleanup(new Error(
                    `${label} did not prefer the exact Java class source while using a decompiled per-member supplement: ${JSON.stringify(raw)}`
                ));
                return;
            }
            requestSemanticEvidence();
        }

        function requestSemanticEvidence() {
            send({
                jsonrpc: '2.0',
                id: semanticRequestIds.hover,
                method: 'textDocument/hover',
                params: {
                    textDocument: { uri: sourceUri },
                    position: fixture.positions.method
                }
            });
            send({
                jsonrpc: '2.0',
                id: semanticRequestIds.completion,
                method: 'textDocument/completion',
                params: {
                    textDocument: { uri: sourceUri },
                    position: fixture.positions.completion
                }
            });
            send({
                jsonrpc: '2.0',
                id: semanticRequestIds.signature,
                method: 'textDocument/signatureHelp',
                params: {
                    textDocument: { uri: sourceUri },
                    position: fixture.positions.signature,
                    context: {
                        triggerKind: 1,
                        isRetrigger: false
                    }
                }
            });
            send({
                jsonrpc: '2.0',
                id: semanticRequestIds.references,
                method: 'textDocument/references',
                params: {
                    textDocument: { uri: sourceUri },
                    position: fixture.positions.method,
                    context: { includeDeclaration: true }
                }
            });
        }

        function recordSemanticEvidence(kind, valid, result) {
            if (!valid) {
                cleanup(new Error(
                    `${label} returned invalid JRuby ${kind} evidence: ${JSON.stringify(result)}`
                ));
                return;
            }
            semanticEvidence.add(kind);
            if (semanticEvidence.size === Object.keys(semanticRequestIds).length) {
                send({
                    jsonrpc: '2.0',
                    id: statusRequestId,
                    method: 'ruby-fast-lsp/runtime/status',
                    params: { projectRoot: fixture.project }
                });
            }
        }

        function handleMessage(message) {
            if (message.method && message.id !== undefined) {
                if (message.method === 'client/registerCapability') {
                    send({ jsonrpc: '2.0', id: message.id, result: null });
                    return;
                }
                send({
                    jsonrpc: '2.0',
                    id: message.id,
                    error: { code: -32601, message: `Unsupported smoke client request: ${message.method}` }
                });
                return;
            }
            if (message.id === 1) {
                if (!message.result?.capabilities) {
                    cleanup(new Error(`Unexpected initialize response: ${JSON.stringify(message)}`));
                    return;
                }
                send({ jsonrpc: '2.0', method: 'initialized', params: {} });
                return;
            }
            if (
                message.method === '$/progress' &&
                message.params?.token === 'indexing' &&
                message.params?.value?.kind === 'end' &&
                !indexingEnded
            ) {
                indexingEnded = true;
                openAndRequestDefinition();
                return;
            }
            if (definitionRequestIds.has(message.id)) {
                definitionRequestIds.delete(message.id);
                validateDefinition(message);
                return;
            }
            if (classDefinitionRequestIds.has(message.id)) {
                classDefinitionRequestIds.delete(message.id);
                validateClassDefinition(message);
                return;
            }
            if (message.id === semanticRequestIds.hover) {
                recordSemanticEvidence(
                    'hover',
                    message.result &&
                        JSON.stringify(message.result).includes('Java::JavaUtil::List'),
                    message.result
                );
                return;
            }
            if (message.id === semanticRequestIds.completion) {
                const items = Array.isArray(message.result)
                    ? message.result
                    : message.result?.items || [];
                recordSemanticEvidence(
                    'completion',
                    items.some(item => item?.label === 'combine'),
                    message.result
                );
                return;
            }
            if (message.id === semanticRequestIds.signature) {
                const signatures = message.result?.signatures || [];
                recordSemanticEvidence(
                    'signature help',
                    signatures.some(signature =>
                        signature?.label?.includes('combine') &&
                        (signature.parameters?.length || 0) === 2
                    ),
                    message.result
                );
                return;
            }
            if (message.id === semanticRequestIds.references) {
                const references = Array.isArray(message.result) ? message.result : [];
                recordSemanticEvidence(
                    'references',
                    references.length >= 2 &&
                        references.some(reference =>
                            (reference?.uri || '').startsWith('file:')
                        ),
                    message.result
                );
                return;
            }
            if (message.id === statusRequestId) {
                const status = message.result?.projects?.[0];
                if (
                    !implementationLocated ||
                    status?.implementation !== 'jruby' ||
                    status?.engineVersion !== '9.2.21.0' ||
                    status?.compatibilityVersion !== '2.5' ||
                    status?.stubOverlay !== '9.2' ||
                    !/^[0-9a-f]{64}$/.test(status?.classpathFingerprintSha256 || '') ||
                    status?.indexingComplete !== true
                ) {
                    cleanup(new Error(
                        `${label} returned invalid runtime status after implementation navigation: ${JSON.stringify(message.result)}`
                    ));
                    return;
                }
                cleanup();
            }
        }

        child.stderr.on('data', chunk => { stderr += chunk.toString(); });
        child.on('error', cleanup);
        child.on('exit', code => {
            if (!settled) {
                cleanup(new Error(`${label} exited before implementation navigation completed with status ${code}`));
            }
        });
        child.stdout.on('data', chunk => {
            stdout = Buffer.concat([stdout, chunk]);
            while (true) {
                const headerEnd = stdout.indexOf('\r\n\r\n');
                if (headerEnd < 0) return;
                const header = stdout.subarray(0, headerEnd).toString();
                const length = Number(header.match(/Content-Length:\s*(\d+)/i)?.[1]);
                if (!Number.isInteger(length)) {
                    cleanup(new Error(`${label} response omitted Content-Length`));
                    return;
                }
                const bodyStart = headerEnd + 4;
                if (stdout.length < bodyStart + length) return;
                const message = JSON.parse(stdout.subarray(bodyStart, bodyStart + length).toString());
                stdout = stdout.subarray(bodyStart + length);
                handleMessage(message);
                if (settled) return;
            }
        });

        send({
            jsonrpc: '2.0',
            id: 1,
            method: 'initialize',
            params: {
                rootUri: projectUri,
                workspaceFolders: [{ uri: projectUri, name: 'jruby-package-smoke' }],
                capabilities: {},
                initializationOptions: {
                    ...initializationOptions,
                    runtime: {
                        mode: 'auto',
                        projects: [{
                            root: runtimeRoot,
                            selection: {
                                implementation: 'jruby',
                                family: '9.2',
                                engineVersion: '9.2.21.0',
                                compatibilityVersion: '2.5',
                                executable: fixture.jrubyExecutable,
                                discoverySource: 'rvm',
                                javaHome: fixture.javaHome
                            }
                        }]
                    },
                    jruby: {
                        mode: 'auto',
                        projects: [{
                            root: runtimeRoot,
                            additionalClasspath: ['lib/rich.jar'],
                            additionalSources: []
                        }]
                    }
                }
            }
        });

        timer = setTimeout(() => {
            cleanup(new Error(
                `${label} timed out waiting for packaged JRuby implementation navigation`
            ));
        }, TIMEOUT_MS);
    });
}

module.exports = {
    runPackagedJrubyNavigationSmoke
};
