[build.env]
passthrough = ["RUST_BACKTRACE", "CARGO_HTTP_DEBUG"]

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"

[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:main"
xargo = false
pre-build = ["apt-get update && apt-get install -y mingw-w64 clang libclang-dev"]
env = { "BINDGEN_EXTRA_CLANG_ARGS_x86_64-pc-windows-gnu" = "--target=x86_64-w64-mingw32 -I/usr/x86_64-w64-mingw32/include -I/usr/share/mingw-w64/include" }
