use std::ops::Range;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmbeddedRuby {
    source: String,
    ruby_ranges: Vec<Range<usize>>,
    unclosed_tag_offset: Option<usize>,
}

impl EmbeddedRuby {
    pub fn source(&self) -> &str {
        &self.source
    }

    pub fn is_ruby_offset(&self, offset: usize) -> bool {
        self.ruby_ranges
            .iter()
            .any(|range| range.start <= offset && offset < range.end)
    }

    pub fn unclosed_tag_offset(&self) -> Option<usize> {
        self.unclosed_tag_offset
    }
}

pub fn is_erb_path(path: &str) -> bool {
    [".erb", ".rhtml", ".rhtm"]
        .iter()
        .any(|extension| path.ends_with(extension))
}

pub fn mask_erb(template: &str) -> EmbeddedRuby {
    let bytes = template.as_bytes();
    let mut masked = vec![b' '; bytes.len()];
    for (index, byte) in bytes.iter().copied().enumerate() {
        if byte == b'\n' || byte == b'\r' {
            masked[index] = byte;
        }
    }

    let mut ruby_ranges = Vec::new();
    let mut cursor = 0usize;
    let mut unclosed_tag_offset = None;
    while let Some(relative_open) = find_bytes(&bytes[cursor..], b"<%") {
        let open = cursor + relative_open;
        let marker = bytes.get(open + 2).copied();
        let search_start = open.saturating_add(3).min(bytes.len());
        let Some(relative_close) = find_bytes(&bytes[search_start..], b"%>") else {
            unclosed_tag_offset = Some(open);
            break;
        };
        let close = search_start + relative_close;
        cursor = close + 2;

        if marker == Some(b'%') || marker == Some(b'#') {
            continue;
        }

        let mut body_start = open + 2;
        if bytes.get(body_start) == Some(&b'-') {
            body_start += 1;
        }
        if bytes.get(body_start) == Some(&b'=') {
            body_start += 1;
        }
        let mut body_end = close;
        if body_end > body_start && bytes.get(body_end - 1) == Some(&b'-') {
            body_end -= 1;
        }
        if body_start >= body_end {
            continue;
        }

        masked[body_start..body_end].copy_from_slice(&bytes[body_start..body_end]);
        masked[close] = b';';
        ruby_ranges.push(body_start..body_end);
    }

    let source = String::from_utf8(masked).expect(
        "INVARIANT VIOLATED: ERB masking produced invalid UTF-8. This is a bug because host bytes are replaced with ASCII and only complete Ruby source slices are copied. Fix: keep tag boundaries on ASCII delimiters and copy whole byte ranges.",
    );
    assert_eq!(
        source.len(),
        template.len(),
        "INVARIANT VIOLATED: ERB masking changed the source byte length. This is a bug because Prism ranges must remain template byte offsets. Fix: replace host bytes one-for-one and never insert generated bytes."
    );
    EmbeddedRuby {
        source,
        ruby_ranges,
        unclosed_tag_offset,
    }
}

fn find_bytes(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    assert!(
        !needle.is_empty(),
        "INVARIANT VIOLATED: ERB byte search received an empty needle. This is a bug because an empty delimiter would make scanner progress undefined. Fix: search only concrete ERB delimiters."
    );
    haystack
        .windows(needle.len())
        .position(|window| window == needle)
}

#[cfg(test)]
mod tests {
    use super::{is_erb_path, mask_erb};
    use crate::core::SourceFileId;
    use crate::indexer::SourceDocument;

    #[test]
    fn masks_host_text_without_moving_ruby_offsets() {
        let template = "<h1>Hello</h1>\n<%= user.name %>\n<% if user.admin? %>admin<% end %>\n";
        let embedded = mask_erb(template);

        assert_eq!(embedded.source().len(), template.len());
        assert_eq!(
            embedded.source().as_bytes()[template.find("user.name").unwrap()],
            b'u'
        );
        assert_eq!(
            embedded.source().as_bytes()[template.find("<h1>").unwrap()],
            b' '
        );
        assert_eq!(
            ruby_prism::parse(embedded.source().as_bytes())
                .errors()
                .count(),
            0
        );
    }

    #[test]
    fn preserves_template_utf16_positions_with_multibyte_host_text() {
        let template = "😀你好 <%= Account.find(1) %>\n";
        let embedded = mask_erb(template);
        let offset = template.find("Account").unwrap();
        let document = SourceDocument::new(template, SourceFileId(7));

        assert_eq!(embedded.source().len(), template.len());
        assert_eq!(document.offset_to_line_character(template, offset), (0, 9));
        assert!(embedded.is_ruby_offset(offset));
        assert!(!embedded.is_ruby_offset(0));
    }

    #[test]
    fn comments_escaped_tags_and_unclosed_tags_do_not_become_ruby() {
        let template = "<%# MissingConstant %>\n<%% ignored %>\n<%= valid_call %>\n<% broken";
        let embedded = mask_erb(template);

        assert!(!embedded.source().contains("MissingConstant"));
        assert!(!embedded.source().contains("ignored"));
        assert!(embedded.source().contains("valid_call"));
        assert!(!embedded.source().contains("broken"));
        assert_eq!(
            embedded.unclosed_tag_offset(),
            Some(template.rfind("<%").unwrap())
        );
    }

    #[test]
    fn trim_markers_keep_only_the_ruby_body() {
        let template = "<%- items.each do |item| -%>\n<%= item.name %>\n<%- end -%>\n";
        let embedded = mask_erb(template);

        assert!(embedded.source().contains("items.each do |item|"));
        assert!(embedded.source().contains("item.name"));
        assert_eq!(
            ruby_prism::parse(embedded.source().as_bytes())
                .errors()
                .count(),
            0
        );
    }

    #[test]
    fn recognizes_supported_embedded_template_paths() {
        assert!(is_erb_path("/views/show.html.erb"));
        assert!(is_erb_path("/views/show.rhtml"));
        assert!(is_erb_path("/views/show.rhtm"));
        assert!(!is_erb_path("/views/show.html"));
        assert!(!is_erb_path("/views/not_erb"));
    }
}
