id = "minitest-ruby"
name = "Minitest Ruby"
version = "0.1.0"
abi_version = 1
server_version = ">=0.2.6, <0.3.0"
runtime = "mruby-wasm"
entry = "extension.rb"
wasm = "extension.wasm"
checksum_sha256 = "55b5b9c9ef93dc247566ea6b82e65d21e4c876792e77f02e1e0a055d38d549f2"
capabilities = ["document_symbol", "code_lens"]
permissions = []

[build]
output = "extension.wasm"
