//! Build script to embed core RBS type definitions into the binary.
//!
//! This script lists every .rbs file under rbs_types/core and generates a Rust
//! module that embeds each one with `include_str!`, so they're available at
//! runtime without needing the files on disk.

use std::env;
use std::fs::{self, File};
use std::io::{BufWriter, Write};
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_rbs.rs");
    let mut file = BufWriter::new(File::create(&dest_path).unwrap());

    writeln!(
        file,
        "// Auto-generated module containing embedded RBS type definitions."
    )
    .unwrap();
    writeln!(file, "// DO NOT EDIT - generated by build.rs").unwrap();
    writeln!(file).unwrap();

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let core_path = Path::new(&manifest_dir).join("rbs_types/core");

    let mut core_files: Vec<(String, PathBuf)> = Vec::new();
    if core_path.exists() {
        collect_rbs_files(&core_path, &core_path, &mut core_files);
    }
    // Directory iteration order is platform-dependent; sort for reproducible output.
    core_files.sort();

    writeln!(
        file,
        "/// Embedded core RBS files (path relative to rbs_types/core, content)"
    )
    .unwrap();
    writeln!(file, "pub static CORE_RBS_FILES: &[(&str, &str)] = &[").unwrap();
    for (name, path) in &core_files {
        writeln!(file, "    ({:?}, include_str!({:?})),", name, path).unwrap();
    }
    writeln!(file, "];").unwrap();

    // Tell Cargo to rerun if RBS files change
    println!("cargo:rerun-if-changed=rbs_types/");
}

fn collect_rbs_files(base_path: &Path, current_path: &Path, files: &mut Vec<(String, PathBuf)>) {
    if let Ok(entries) = fs::read_dir(current_path) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_rbs_files(base_path, &path, files);
            } else if path.extension().is_some_and(|ext| ext == "rbs") {
                let relative = path.strip_prefix(base_path).unwrap_or(&path);
                let name = relative.to_string_lossy().replace('\\', "/");
                files.push((name, path));
            }
        }
    }
}
