id = "rails-ruby"
name = "Rails Ruby"
version = "0.1.0"
abi_version = 1
server_version = ">=0.2.6, <0.3.0"
runtime = "mruby-wasm"
entry = "extension.rb"
wasm = "extension.wasm"
checksum_sha256 = "e25208f18d6a5016a4fe40560368754b0facaa1a20f81d8ca1f4ffb8eafcfcef"
capabilities = ["index.call"]
permissions = []

[build]
output = "extension.wasm"

[indexing]
call_names = ["belongs_to", "has_one", "has_many"]
